server:
  port: 8801
spring:
  application:
    name: seata-order8801
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/seata?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: jmq_seata
management:
  endpoints:
    web:
      exposure:
        include: "*"